Name:           ros-lunar-cartographer
Version:        0.2.0
Release:        2%{?dist}
Summary:        ROS cartographer package

Group:          Development/Libraries
License:        Apache 2.0
URL:            https://github.com/googlecartographer/cartographer
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       cairo-devel
Requires:       ceres-solver-devel
Requires:       eigen3-devel
Requires:       gflags-devel
Requires:       glog-devel
Requires:       libwebp-devel
Requires:       lua
Requires:       protobuf-compiler
Requires:       protobuf-devel
BuildRequires:  boost-devel
BuildRequires:  cairo-devel
BuildRequires:  ceres-solver-devel
BuildRequires:  eigen3-devel
BuildRequires:  gcc-c++
BuildRequires:  gflags-devel
BuildRequires:  glibc-devel
BuildRequires:  glibc-static
BuildRequires:  glog-devel
BuildRequires:  gmock-devel
BuildRequires:  libstdc++-devel
BuildRequires:  libstdc++-static
BuildRequires:  libwebp-devel
BuildRequires:  lua
BuildRequires:  protobuf-compiler
BuildRequires:  protobuf-devel
BuildRequires:  python-sphinx
BuildRequires:  ros-lunar-catkin

%description
Cartographer is a system that provides real-time simultaneous localization and
mapping (SLAM) in 2D and 3D across multiple platforms and sensor configurations.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Fri Mar 30 2018 The Cartographer Owners <cartographer-owners@googlegroups.com> - 0.2.0-2
- Autogenerated by Bloom

* Fri Mar 30 2018 The Cartographer Owners <cartographer-owners@googlegroups.com> - 0.2.0-1
- Autogenerated by Bloom

* Sun Dec 17 2017 Mikael Arguedas <mikael@osrfoundation.org> - 0.3.0-0
- Autogenerated by Bloom

* Thu Sep 28 2017 Mikael Arguedas <mikael@osrfoundation.org> - 0.2.0-0
- Autogenerated by Bloom

